# List available recipes
help:
    @just --list --unsorted

# Install alacritty
install:
    @echo "Installing alacritty"
    sudo dnf install -y alacritty

# Configure alacritty
configure:
    @echo "Stowing config files"
    stow .

# Post-install setup
post-install:

# Factory reset tmux
reset:
    @echo "Removing config files"
    stow --delete .
