distro := shell("cat /etc/os-release | grep ^ID= | cut -d = -f 2")

# List available recipes
help:
    @just --list --unsorted

# Install ghostty
install:
    @echo "Installing ghostty"
    just _install-{{ distro }}

_install-ubuntu:
    sudo snap install ghostty --classic

_install-fedora:
    sudo dnf install -y ghostty

# Configure ghostty
configure:
    @echo "Stowing config files"
    stow .

# Post-install setup of ghostty
post-install:

# Factory reset ghostty
reset:
    @echo "Removing config files"
    stow --delete .
