# List available recipes
help:
    @just --list --unsorted

# Install ghostty
install:
    @echo "Installing ghostty"
    sudo dnf install -y ghostty

# Configure ghostty
configure:
    @echo "Stowing config files"
    stow .

# Post-install setup of ghostty
post-install:

# Factory reset ghostty
reset:
    @echo "Removing config files"
    stow --delete .
