# List available recipes
help:
    @just --list --unsorted

# Install starship
install:
    @echo "Installing starship"
    nix profile add nixpkgs#starship

# Configure starship
configure:
    @echo "Stowing config file"
    stow .

# Post-install
post-install:

# Update starship
update: install

# Remove starship
remove:
    @echo "Cleaning up config."
    stow --delete .
    @echo "Removing starship binary"
    sudo sh -c 'rm "$(command -v 'starship')"'
