# List available recipes
help:
    @just --list --unsorted

# Install mise
install:
    @echo "Installing mise"
    curl https://mise.run | sh

# Configure mise
configure:
    @echo "Stowing config files"
    stow .

# Post-install
post-install:
    @echo "Installing tools"
    mise install

# Update mise
update:
    mise self-update

# Remove mise
remove:
    @echo "Cleaning up bashrc."
    stow --delete .
    mise implode
    @echo "Close and reopen shell"
