# List available recipes
help:
    @just --list --unsorted

# Install neovim
install:
    sudo dnf -y install neovim

# Configure LazyVim distro
configure:
    git clone https://github.com/LazyVim/starter "$HOME/.config/nvim"
    stow -t "$HOME" -v config

# Factory reset neovim config
reset:
    rm -rf "$HOME/.config/nvim" \
        "$HOME/.local/share/nvim" \
        "$HOME/.local/state/nvim" \
        "$HOME/.cache/nvim"
