# List available recipes
help:
    @just --list --unsorted

# Install fonts
install:
    @echo "Installing fonts"
    mkdir -p "$HOME/.config/fontconfig"
    mkdir -p "$HOME/.local/share/fonts"
    stow -t "$HOME/.config/fontconfig" fontconfig
    stow -t "$HOME/.local/share/fonts" fonts
    fc-cache -fv

# Remove installed fonts
remove:
    @echo "Removing installed fonts"
    stow --delete -t "$HOME/.config/fontconfig" fontconfig
    stow --delete -t "$HOME/.local/share/fonts" fonts
    fc-cache -fv
