distro := shell("cat /etc/os-release | grep ^ID= | cut -d = -f 2")

# List available recipes
help:
    @just --list --unsorted

# Install fzf
install:
    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
    $HOME/.fzf/install

# Configure fzf
configure:

# Post-install setup
post-install:

# Factory reset
reset: remove

# Remove fzf
remove:
    rm -rf $HOME/.fzf $HOME/.fzf.bash
