# List available recipes
help:
    @just --list --unsorted

# Install fzf
install:
    sudo dnf install -y fzf

# Configure fzf
configure:
    @echo "Configuring bashrc."
    stow .

# Post-install setup
post-install:

# Factory reset
reset:
    @echo "Cleaning up bashrc."
    stow --delete .

# Remove fzf
remove:
