distro := shell("cat /etc/os-release | grep ^ID= | cut -d = -f 2")

# List available recipes
help:
    @just --list --unsorted

# Install base tools
install:
    just _install-{{ distro }}

_install-ubuntu:
    sudo apt install -y \
      bat \
      build-essential \
      cloc \
      dconf-editor \
      fd-find \
      ripgrep \
      gnome-tweaks \
      ;
    brew install \
      lazygit \
      ;

_install-fedora:
    sudo dnf copr enable -y \
      atim/lazygit \
      ;

    sudo dnf install -y \
      bat \
      cloc \
      fd-find \
      lazygit \
      ;

