distro := shell("cat /etc/os-release | grep ^ID= | cut -d = -f 2")

# List available recipes
help:
    @just --list --unsorted

# Install base tools
install:
    just _install-{{ distro }}

_install-ubuntu:
    sudo apt install -y \
      build-essential \
      ;

    nix profile add \
      nixpkgs#bat \
      nixpkgs#cloc \
      nixpkgs#dconf-editor \
      nixpkgs#fd \
      nixpkgs#gnome-tweaks \
      nixpkgs#lazygit \
      nixpkgs#ripgrep \
      ;

    sudo snap install --classic obsidian

_install-fedora:
    sudo dnf copr enable -y \
      atim/lazygit \
      ;

    sudo dnf install -y \
      bat \
      cloc \
      fd-find \
      lazygit \
      ;

