# List available recipes
help:
    @just --list --unsorted

# Install git version control system
git:
    sudo apt update
    sudo apt install git

# Install sdkman - Software Development Kit Manager
sdkman:
    curl -s "https://get.sdkman.io" | bash

# Install pnpm - Fast, disk space efficient package manager
pnpm:
    curl -fsSL https://get.pnpm.io/install.sh | sh -

# Install nodejs using pnpm
node: pnpm
    pnpm env use --global lts
