# List available recipes
help:
    @just --list --unsorted

# Install base tools
install:
    sudo dnf copr enable -y \
      atim/lazygit \
      ;

    sudo dnf install -y \
      bat \
      cloc \
      fd-find \
      lazygit \
      ;


