local_repo := "$HOME/.local/share/dircolors"

# List available recipes
help:
    @just --list --unsorted

# Install nord dircolors
install:
    git clone git@github.com:nordtheme/dircolors.git {{ local_repo }}

# Configure nord dircolors
configure:
    @echo "Configuring bashrc."
    stow .

# Post-install setup
post-install:

# Factory reset
reset: remove

# Remove nord dircolors
remove:
    @echo "Cleaning up bashrc."
    stow --delete .
    @echo "Removing nord dircolors directory"
    rm -rf {{ local_repo }}
